export const ActionPhase = Object.freeze({
  None: 'None',
  Startup: 'Startup',
  Active: 'Active',
  Recovery: 'Recovery',
  Finished: 'Finished',
});

export const ActorState = Object.freeze({
  Locomotion: 'Locomotion',
  AutoAttack: 'AutoAttack',
  Art: 'Art',
});

export const EnemyState = Object.freeze({
  Idle: 'Idle',
  Attacking: 'Attacking',
  Cooldown: 'Cooldown',
  Controlled: 'Controlled',
  Dead: 'Dead',
});

export const ActionKind = Object.freeze({
  AutoAttack: 'AutoAttack',
  Art: 'Art',
  EnemyStrike: 'EnemyStrike',
});

export const DriverComboStage = Object.freeze({
  None: 'None',
  Break: 'Break',
  Topple: 'Topple',
  Launch: 'Launch',
});

export const DriverComboEffect = Object.freeze({
  Break: 'Break',
  Topple: 'Topple',
  Launch: 'Launch',
  Smash: 'Smash',
});

export const BladeComboElement = Object.freeze({
  Fire: 'Fire',
  Water: 'Water',
});

export const BladeComboStage = Object.freeze({
  None: 'None',
  Stage1: 'Stage1',
  Stage2: 'Stage2',
});

export const CombatEventType = Object.freeze({
  Init: 'Init',
  Reset: 'Reset',
  BattleStarted: 'BattleStarted',
  InputBuffered: 'InputBuffered',
  InputConsumed: 'InputConsumed',
  InputExpired: 'InputExpired',
  DebugGrantArtsReady: 'DebugGrantArtsReady',
  DebugGrantSpecialReady: 'DebugGrantSpecialReady',
  ActionStarted: 'ActionStarted',
  ActionPhaseChanged: 'ActionPhaseChanged',
  ActionHit: 'ActionHit',
  ActionWhiffed: 'ActionWhiffed',
  ActionFinished: 'ActionFinished',
  EnemyTargetSelected: 'EnemyTargetSelected',
  EnemyAttackStarted: 'EnemyAttackStarted',
  EnemyAttackPhaseChanged: 'EnemyAttackPhaseChanged',
  EnemyAttackHit: 'EnemyAttackHit',
  EnemyAttackWhiffed: 'EnemyAttackWhiffed',
  EnemyAttackFinished: 'EnemyAttackFinished',
  EnemyAttackCooldownStarted: 'EnemyAttackCooldownStarted',
  EnemyAttackCooldownFinished: 'EnemyAttackCooldownFinished',
  EnemyAttackInterrupted: 'EnemyAttackInterrupted',
  EnemyControlled: 'EnemyControlled',
  EnemyStrikeStarted: 'EnemyStrikeStarted',
  EnemyStrikePhaseChanged: 'EnemyStrikePhaseChanged',
  EnemyStrikeHit: 'EnemyStrikeHit',
  EnemyStrikeWhiffed: 'EnemyStrikeWhiffed',
  EnemyStrikeInterrupted: 'EnemyStrikeInterrupted',
  EnemyStrikeFinished: 'EnemyStrikeFinished',
  PlayerDamageApplied: 'PlayerDamageApplied',
  DamageApplied: 'DamageApplied',
  TargetHpChanged: 'TargetHpChanged',
  TargetDefeated: 'TargetDefeated',
  PlayerHpChanged: 'PlayerHpChanged',
  PlayerDefeated: 'PlayerDefeated',
  BattleEnded: 'BattleEnded',
  ArtChargeChanged: 'ArtChargeChanged',
  ArtBecameReady: 'ArtBecameReady',
  ArtConsumed: 'ArtConsumed',
  SpecialChargeChanged: 'SpecialChargeChanged',
  SpecialBecameReady: 'SpecialBecameReady',
  SpecialConsumed: 'SpecialConsumed',
  SpecialCastFailed: 'SpecialCastFailed',
  SpecialHit: 'SpecialHit',
  CancelBonusWindowOpened: 'CancelBonusWindowOpened',
  CancelBonusApplied: 'CancelBonusApplied',
  RecoveryCanceledToMovement: 'RecoveryCanceledToMovement',
  RecoveryCanceledToArt: 'RecoveryCanceledToArt',
  AutoAttackChainAdvanced: 'AutoAttackChainAdvanced',
  AutoAttackChainReset: 'AutoAttackChainReset',
  BackpackResolved: 'BackpackResolved',
  BackpackInvalid: 'BackpackInvalid',
  DriverComboApplied: 'DriverComboApplied',
  DriverComboAdvanced: 'DriverComboAdvanced',
  DriverComboRefreshed: 'DriverComboRefreshed',
  DriverComboFailed: 'DriverComboFailed',
  DriverComboExpired: 'DriverComboExpired',
  DriverComboFinished: 'DriverComboFinished',
  BladeComboStarted: 'BladeComboStarted',
  BladeComboAdvanced: 'BladeComboAdvanced',
  BladeComboFailed: 'BladeComboFailed',
  BladeComboExpired: 'BladeComboExpired',
  BladeComboFinished: 'BladeComboFinished',
  BladeLinked: 'BladeLinked',
  BladeSocketResolved: 'BladeSocketResolved',
  BladeAttackStarted: 'BladeAttackStarted',
  BladeAttackPhaseChanged: 'BladeAttackPhaseChanged',
  BladeAttackHit: 'BladeAttackHit',
  BladeAttackWhiffed: 'BladeAttackWhiffed',
  BladeAttackFinished: 'BladeAttackFinished',
  BladeAttackCooldownStarted: 'BladeAttackCooldownStarted',
  BladeAttackCooldownFinished: 'BladeAttackCooldownFinished',
  TokenCreated: 'TokenCreated',
  RoutineTileAdded: 'RoutineTileAdded',
  RoutineTileRemoved: 'RoutineTileRemoved',
  RoutineOrbCreated: 'RoutineOrbCreated',
  RoutineOrbReplaced: 'RoutineOrbReplaced',
  RoutineOrbBreakFailed: 'RoutineOrbBreakFailed',
  RoutineOrbBreakStarted: 'RoutineOrbBreakStarted',
  RoutineOrbBroken: 'RoutineOrbBroken',
  RoutineOrbBreakFinished: 'RoutineOrbBreakFinished',
  ElementDamageApplied: 'ElementDamageApplied',
  DebuffApplied: 'DebuffApplied',
  DebuffTickDamage: 'DebuffTickDamage',
  DebuffExpired: 'DebuffExpired',
});
